# Generated by Django 2.2.11 on 2022-06-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.IntegerField(verbose_name='学分'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.IntegerField(default=1, verbose_name='课程状态'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='5分为最满意，最低分是1分', null=True, verbose_name='学生评分'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='with_draw',
            field=models.BooleanField(default=False),
        ),
    ]
