# Generated by Django 2.2.11 on 2022-06-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacher',
            name='teacher_id',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='department_nu',
            new_name='department_no',
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('department_no', 'number'), name='teacher_id'),
        ),
    ]
